# Generated by Django 3.2.4 on 2021-06-21 07:13

from django.db import migrations, models
import django.db.models.deletion
from ..models import Position, Employee


def load_data(apps, schema_editor):
    Position = apps.get_model("empApp", "Position")
    Employee = apps.get_model("empApp", "Employee")

    position = Position(name="Программиист")
    position.save()
    employee = Employee(first_name="First name", last_name="Last name", position=position)
    employee.save()

    position = Position(name="Младший программиист")
    position.save()
    employee = Employee(first_name="First name 1", last_name="Last name 1", position=position)
    employee.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empApp.position')),
            ],
        ),
        migrations.RunPython(load_data)
    ]
