# Generated by Django 3.2.4 on 2021-06-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='first_name',
        ),
    ]
